import ALPHABET_SCALE from './ALPHABET_SCALE'
import LOAD_DATA from './LOAD_DATA'
import COLOR_LIST from './COLOR_LIST'
import DEFAULT_CONFIG from './DEFAULT_CONFIG'
import THEMES from './THEMES'
const CONSTS = {
	ALPHABET_SCALE,
	LOAD_DATA,
	COLOR_LIST,
	DEFAULT_CONFIG,
	THEMES
}
export default CONSTS;